CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS $WP_USER_LOGIN @'%' IDENTIFIED BY $WP_USER_PASSWORD;
GRANT ALL PRIVILEGES ON wordpress.* TO $WP_USER_LOGIN @'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
