CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS $DB_USR@'%' IDENTIFIED BY $DB_PWD;
GRANT ALL PRIVILEGES ON wordpress.* TO $DB_USR@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
